export enum ApiErrorCode {
  EMPTY_REQUEST_BODY = "EMPTY_REQUEST_BODY",
  INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY",
  SOMETHING_BAD_HAPPENED = "SOMETHING_BAD_HAPPENED",
  //Login
  EMAIL_DOES_NOT_EXISTS = "EMAIL_DOES_NOT_EXISTS",
  WRONG_PASSWORD = "WRONG_PASSWORD",
}
